name: Generate Logos

on:
  push:
    branches: [ main ]
    paths:
      - 'identities.yml'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        
    - name: Generate
      working-directory: scripts/logo-generate
      env:
        OUTPUT_PATH: ${{ github.workspace }}/assets/logos
        IDENTITIES_PATH: ${{ github.workspace }}/identities.yml
      run: |
        npm ci
        node index
        
    - name: Commit Logos
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        branch: main
        commit_message: 'chore: update logos [skip ci]'
        file_pattern: assets/logos/*.svg
